//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintNCI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Print_Jaminan_Askes_IGD_FromBill.exe")]
        public string ExecutablePrintAskes {
            get {
                return ((string)(this["ExecutablePrintAskes"]));
            }
            set {
                this["ExecutablePrintAskes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Print_Jaminan_Jamkesmas_IGD_FromBill.exe")]
        public string ExecutablePrintJamkesmasRWJ {
            get {
                return ((string)(this["ExecutablePrintJamkesmasRWJ"]));
            }
            set {
                this["ExecutablePrintJamkesmasRWJ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UntukUGD {
            get {
                return ((bool)(this["UntukUGD"]));
            }
            set {
                this["UntukUGD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Print_Jaminan_Jamkesmas_RWI.exe")]
        public string ExecutablePrintJamkesmasRWI {
            get {
                return ((string)(this["ExecutablePrintJamkesmasRWI"]));
            }
            set {
                this["ExecutablePrintJamkesmasRWI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PrintNCI.log")]
        public string LogFileName {
            get {
                return ((string)(this["LogFileName"]));
            }
            set {
                this["LogFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Logging {
            get {
                return ((bool)(this["Logging"]));
            }
            set {
                this["Logging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NCICetakStatusRI.tmp")]
        public string RITempFileName {
            get {
                return ((string)(this["RITempFileName"]));
            }
            set {
                this["RITempFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RawatInap {
            get {
                return ((bool)(this["RawatInap"]));
            }
            set {
                this["RawatInap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Print_Jaminan_Jamkesda_IGD_FromBill.exe")]
        public string ExecutablePrintJamkesdaRWJ {
            get {
                return ((string)(this["ExecutablePrintJamkesdaRWJ"]));
            }
            set {
                this["ExecutablePrintJamkesdaRWJ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NCICetakStatus.tmp")]
        public string RJTempFileName {
            get {
                return ((string)(this["RJTempFileName"]));
            }
            set {
                this["RJTempFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Print_Status_Pasien.exe")]
        public string ExecutablePrintStatus {
            get {
                return ((string)(this["ExecutablePrintStatus"]));
            }
            set {
                this["ExecutablePrintStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Print_Jaminan_In_Health_IGD_FromBill.exe")]
        public string ExecutablePrintInHealth {
            get {
                return ((string)(this["ExecutablePrintInHealth"]));
            }
            set {
                this["ExecutablePrintInHealth"] = value;
            }
        }
    }
}
