#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintNCI
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="RSKUPANG")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClassesDataContext() : 
				base(global::PrintNCI.Properties.Settings.Default.RSKUPANGConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[Function(Name="dbo.RSUD_GET_INFO_KUNJUNGAN")]
		public ISingleResult<RSUD_GET_INFO_KUNJUNGANResult> RSUD_GET_INFO_KUNJUNGAN([Parameter(Name="KD_KASIR", DbType="VarChar(2)")] string kD_KASIR, [Parameter(Name="NO_TRANSAKSI", DbType="VarChar(5)")] string nO_TRANSAKSI)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), kD_KASIR, nO_TRANSAKSI);
			return ((ISingleResult<RSUD_GET_INFO_KUNJUNGANResult>)(result.ReturnValue));
		}
	}
	
	public partial class RSUD_GET_INFO_KUNJUNGANResult
	{
		
		private string _KD_PASIEN;
		
		private System.DateTime _TGL_MASUK;
		
		private string _KD_UNIT;
		
		private short _URUT_MASUK;
		
		private bool _BARU;
		
		private string _CUSTOMER;
		
		private byte _KD_BAGIAN;
		
		public RSUD_GET_INFO_KUNJUNGANResult()
		{
		}
		
		[Column(Storage="_KD_PASIEN", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string KD_PASIEN
		{
			get
			{
				return this._KD_PASIEN;
			}
			set
			{
				if ((this._KD_PASIEN != value))
				{
					this._KD_PASIEN = value;
				}
			}
		}
		
		[Column(Storage="_TGL_MASUK", DbType="DateTime NOT NULL")]
		public System.DateTime TGL_MASUK
		{
			get
			{
				return this._TGL_MASUK;
			}
			set
			{
				if ((this._TGL_MASUK != value))
				{
					this._TGL_MASUK = value;
				}
			}
		}
		
		[Column(Storage="_KD_UNIT", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string KD_UNIT
		{
			get
			{
				return this._KD_UNIT;
			}
			set
			{
				if ((this._KD_UNIT != value))
				{
					this._KD_UNIT = value;
				}
			}
		}
		
		[Column(Storage="_URUT_MASUK", DbType="SmallInt NOT NULL")]
		public short URUT_MASUK
		{
			get
			{
				return this._URUT_MASUK;
			}
			set
			{
				if ((this._URUT_MASUK != value))
				{
					this._URUT_MASUK = value;
				}
			}
		}
		
		[Column(Storage="_BARU", DbType="Bit NOT NULL")]
		public bool BARU
		{
			get
			{
				return this._BARU;
			}
			set
			{
				if ((this._BARU != value))
				{
					this._BARU = value;
				}
			}
		}
		
		[Column(Storage="_CUSTOMER", DbType="VarChar(40)")]
		public string CUSTOMER
		{
			get
			{
				return this._CUSTOMER;
			}
			set
			{
				if ((this._CUSTOMER != value))
				{
					this._CUSTOMER = value;
				}
			}
		}
		
		[Column(Storage="_KD_BAGIAN", DbType="TinyInt NOT NULL")]
		public byte KD_BAGIAN
		{
			get
			{
				return this._KD_BAGIAN;
			}
			set
			{
				if ((this._KD_BAGIAN != value))
				{
					this._KD_BAGIAN = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
